### ISSUE TITLE
Setting AM/PM time in config/locales/en.yml

### ISSUE THREAD

**Issue by digitalplaywright** [slorek/formtastic-date-time-money-fields#1]
First, great work! It's really nice and simple to use.

I am having trouble changing the time-format to AM/PM in  'config/locales/en.yml'. But I am able to change it by modifying the 'ampm' option in the javascript. Do you know how to modify if AM/PM or the 24hr format should be used in the locale? 

I changed this without success
...
time:
  formats:
      default: '%B %d, %Y %H:%M'
...

to

...
time: 
   formats:
      default: '%B %d, %Y %H:%M tt'

**Comment by slorek** [comment]
Hi there,

You may find this site useful: http://strfti.me/ it lists all of the time variables. You probably want something like:

'%B %d, %Y %I:%M %p

I'm closing this because it's not specific to the plugin.
